-- Run this script in the Supabase SQL Editor to set up your tables

-- 1. Create 'courses' table
CREATE TABLE public.courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT,
  "desc" TEXT, -- Quoted because 'desc' is a SQL keyword
  level TEXT,
  format TEXT,
  price TEXT,
  status TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create 'jobs' table
CREATE TABLE public.jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT,
  type TEXT,
  "desc" TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies
-- IMPORTANT: Since we are using a simple admin check on the frontend and the anon key,
-- we'll allow public access for now. In a full production app with Supabase Auth,
-- you would restrict INSERT/UPDATE/DELETE to authenticated admin users.

CREATE POLICY "Enable all access for courses" ON public.courses
FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Enable all access for jobs" ON public.jobs
FOR ALL USING (true) WITH CHECK (true);
